### ISSUE TITLE
 Could not set the Portainer App Templates URL. Check your Portainer settings (URL/USERNAME/PASSWORD). 

### ISSUE THREAD

**Issue by PDXUser** [technorabilia/portainer-tools#1]
Portainer is set to use port 9443 (SSL) per their [instructions](https://docs.portainer.io/start/install/server/docker/linux).  New install tonight and it is not working. This is with Portainer 2.14.  The error I am getting when I tried to set a template is as follows:

> today at 11:12:48 PM192.168.1.160 - - [15/Aug/2022 06:12:48] "GET /socket.io/?EIO=4&transport=polling&t=OAW8YKo&sid=tZFyEpT4yHD1IN3XAAAC HTTP/1.1" 200 -
> **today at 11:12:53 PM192.168.1.160 - - [15/Aug/2022 06:12:53] "POST /apptemplate/2/set HTTP/1.1" 302 -**
> today at 11:12:53 PM192.168.1.160 - - [15/Aug/2022 06:12:53] "GET / HTTP/1.1" 200 -
> today at 11:12:53 PM192.168.1.160 - - [15/Aug/2022 06:12:53] "GET /socket.io/?EIO=4&transport=polling&t=OAW8ZZK HTTP/1.1" 200 -
> today at 11:12:53 PM192.168.1.160 - - [15/Aug/2022 06:12:53] "POST /socket.io/?EIO=4&transport=polling&t=OAW8Za5&sid=8B3DzFJbEP3ySKWtAAAE HTTP/1.1" 200 -
> today at 11:12:53 PM192.168.1.160 - - [15/Aug/2022 06:12:53] "GET /socket.io/?EIO=4&transport=polling&t=OAW8Za7&sid=8B3DzFJbEP3ySKWtAAAE HTTP/1.1" 200 

-

My Docker compose:

> version: '3.3'
> services:
>     portainer-tools:
>         container_name: portainer-tools
>         environment:
>             - PUID=<puid>
>             - PGID=<pgid>
>             - SERVER_URL=https://192.168.1.161
>             - PORTAINER_URL=https://192.168.1.161:9443
>             - PORTAINER_USERNAME=admin
>             - PORTAINER_PASSWORD=MyPasswordhere
>         ports:
>             - 7256:9999
>         volumes:
>             - /mnt/4TB/portainertools:/config
>         restart: unless-stopped
>         image: technorabilia/portainer-tools

I have tried with the non https port of 8000 and get the same result (Setting the environment to http://192.168.1.161:8000).  

I am open to ideas or suggestions on this, as of now with the 302 redirect, I am stumped. 

(edited to make it easier to follow the error log and compose file)

**Comment by technorabilia** [comment]
Indeed, it seems that an SSL connection to Portainer does not work, but without SSL it should.

For this you have to use port `9000` and not port `8000` as you indicate. Port `8000` is for the agent...

I will make a note in the `README` that SSL is a no-go. Unfortunately I don't have time to fix this at the moment.

Thanks for pointing this out.

**Comment by technorabilia** [comment]
I made a [quick fix/hack](https://github.com/technorabilia/portainer-tools/commit/30e9b318b0bf558e507b92116c9993936b267492) to make it work. Not very fancy, but it should do the trick for now.
