### ISSUE TITLE
ARM64 Portation

### ISSUE THREAD

**Issue by zackmuc** [technorabilia/portainer-tools#3]
Is it possible to port it to ARM64 for Raspberry Pi?

**Comment by technorabilia** [comment]
It is not available by default, but maybe you can build your own image by replacing [this](https://github.com/technorabilia/portainer-tools/blob/3869e3af1cebb8cf48b55513c476ee013e273b28/Dockerfile#L1) line by:
`FROM arm64v8/python:3.9-slim`

I'm not familiar with `arm64`, but I think this is how it is suppose to work.

**Comment by zackmuc** [comment]
gut it work hat also to change amd64 to aarch64 then it built. thx. I tries now to merge the 2 linuxservber.io and portainer by selecting both and clicking merge but notthing happens

**Comment by zackmuc** [comment]
Got it to work. also had to change AMD64 to AARCH64 in the file
